# Site settings
title: Lane IT on Github
email: webmaster@lanecc.edu
description: > 
  The homepage of open source projects at Lane Community College in Eugene, Oregon.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: laneit
github_username: lanecommunitycollege

# Build settings
markdown: kramdown
